Header and headline
ZabihullahNooriWardak/portfolio pull request #1
Opened 2023-06-01 03:36 UTC by ZabihullahNooriWardak

2023-06-01 04:37 UTC, ZabihullahNooriWardak commented on style.css
> +}
h1 tag for test

2023-06-01 14:51 UTC, ZabihullahNooriWardak commented
i have done some work on the very first part of the portfolio project

2023-06-02 00:57 UTC, shahadat3669 requested changes
Hi  @ZabihullahNooriWardak , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project that has a couple of areas that need improvement.
- The title of your pull request lacks professionalism. It is essential to have a clear and meaningful title that accurately describes the purpose of the pull request. Consider using titles like "Create a Sidebar for Mobile Menu" or "Add Comments Section for User" that provide a concise summary of the changes made. :+1: Please change the PR title which describes what you did in this PR.

- The pull request description should be descriptive and provide context about the changes being introduced. Take the opportunity to explain the purpose, implementation details, and any relevant information that would help reviewers understand the changes better. :+1: Please change the PR description which describes what you did in this PR.

| Your | Professional |
| --- | --- |
| ![image](https://github.com/ZabihullahNooriWardak/portfolio/assets/55840999/2dcd555a-a137-4e97-8e57-2718f8e924f9) | ![image](https://github.com/KiengPhyl/Philemon-portfolio/assets/55840999/b374f720-1c2a-403e-a589-10b9f49655eb) |

- The README file, please keep in mind that only the FAQ section is optional, all the other sections are important in the README file. Kindly take a look at the original template by clicking [here](https://github.com/microverseinc/readme-template)
I marked some parts of the template you did not implement yet. 
![image](https://github.com/ZabihullahNooriWardak/portfolio/assets/55840999/fa0ab178-913d-4a9e-807c-aad8b330b787)




Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-02 06:02 UTC, shella12 requested changes
Hi @ZabihullahNooriWardak, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Fair attempt at design implementation ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 06:02 UTC, shella12 commented on style.css
> +}
- [ ] Here too the `font` defined for the template for the paragraph is `Poppins` so please make sure to change that as well.

2023-06-02 10:26 UTC, aamirkhan2478 requested changes
Hi @ZabihullahNooriWardak , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 10:26 UTC, aamirkhan2478 commented on style.css
> +}
- [ ] As mentioned by the previous reviewer :point_up_2: Please use the same colors as mentioned in the Figma design but still you are not using the same color of Figma design so kindly replace `background-color: rgb(60, 58, 57);` to `background-color: #3C3A39;` Also please use `logo` and `handburger menu` color `#FFFFFF` :slightly_smiling_face: 
- [ ] As mentioned by the previous reviewer :point_up_2: also please make sure that the section has the margins (top, bottom, left, right) defined in the design but still the height of your navbar is not the same as the Figma design so kindly fix this issue :+1: check below :point_down: the comparison between your design and Figma's design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-06-02 14-59-38](https://github.com/ZabihullahNooriWardak/portfolio/assets/45226848/e3720f4a-1b66-44d4-a0c2-fcb4f641e045)

**Figma Design**
![Screenshot from 2023-06-02 14-59-56](https://github.com/ZabihullahNooriWardak/portfolio/assets/45226848/41067659-4448-41be-818a-56413049a0e4)

2023-06-02 10:26 UTC, aamirkhan2478 commented on style.css
> +}
- [ ] As mentioned by the previous reviewer :point_up_2: please use color `#FF6B00` to match with the Figma design but still you didn't use same color suggested by the previous reviewer so kindly replace `color: rgb(255, 107, 0);` with `color: #FF6B00;` :+1: check below :point_down: the comparison between your design and Figma's design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-06-02 15-19-52](https://github.com/ZabihullahNooriWardak/portfolio/assets/45226848/6a24d93a-e9ae-47eb-b520-b791e520c5d8)

**Figma Design**
![Screenshot from 2023-06-02 15-20-05](https://github.com/ZabihullahNooriWardak/portfolio/assets/45226848/ed389742-74cb-4033-a9fa-3f947aa62580)

- [ ] Also please use same `font size` as mentioned in Figma design :+1:

2023-06-02 10:26 UTC, aamirkhan2478 commented on style.css
> +}
- [ ] As mentioned by the previous reviewer :point_up_2: please use the same color as mentioned by the Figma design so kindly replace your color with `#FFF5E1` :+1:

2023-06-02 13:27 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @ZabihullahNooriWardak , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="375px" />

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] Good design implementation :white_check_mark: 
- [x] Pull request has a descriptive summary and title :white_check_mark: 
- [x]  Repository has a professional readme file :white_check_mark:  
- [x] Implemented changes from the previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 13:57 UTC, merged